### ISSUE TITLE
Could you please provide your pascal-person-part dataset？ 

### ISSUE THREAD

**Issue by Minssnail** [Charleshhy/Grapy-ML#8]
I have downloaded many versions of the pascal-person-part dataset. But I still failed to prepare well of it and cannot reproduce the same results with yours. 

Could you please provide your pascal-person-part dataset？Thank you so much.

**Comment by Charleshhy** [comment]
Hi,

Sorry for the late reply, I thought you were just looking for dataset download link for PASCAL-PERSON-PART and forgot to get back to you. The PASCAL-PERSON-PART dataset that I am using is the same as the online version without modification (which I cannot find the original link anymore but it should all be same). 

The reason for inferior performance can be attributed to the network's random initialisation. You can also try [this](https://github.com/Charleshhy/Grapy-ML/blob/664f59b4aa119cdd2ea7abbb38f640335d5406e0/networks/graph_pyramid.py#L188) function instead, since we found residual connections boost performance on some datasets while not on the other dataests.

Also, can you provide your training log and the highest mIoU that you can achieve for me? So that I can further investigate on this issue. 

Kind regards,
Haoyu

**Comment by Minssnail** [comment]
收到啦！我会尽快回复您。
